# Generated by Django 4.1 on 2022-09-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="팀명"
                    ),
                ),
                (
                    "team_members",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="팀원"
                    ),
                ),
                (
                    "mission",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="미션설명"
                    ),
                ),
                (
                    "mission4_imagesrc1",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지1 주소"
                    ),
                ),
                (
                    "mission4_imagesrc2",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지2 주소"
                    ),
                ),
                (
                    "mission4_imagesrc3",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지3 주소"
                    ),
                ),
                (
                    "mission4_imagesrc4",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지4 주소"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="아이디",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission_4",
                "verbose_name_plural": "Mission_4",
                "db_table": "Mission_4",
            },
        ),
        migrations.CreateModel(
            name="Mission_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="팀명"
                    ),
                ),
                (
                    "team_members",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="팀원"
                    ),
                ),
                (
                    "mission",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="미션설명"
                    ),
                ),
                (
                    "mission3_imagesrc1",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지1 주소"
                    ),
                ),
                (
                    "mission3_imagesrc2",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지2 주소"
                    ),
                ),
                (
                    "mission3_imagesrc3",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지3 주소"
                    ),
                ),
                (
                    "mission3_imagesrc4",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지4 주소"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="아이디",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission_3",
                "verbose_name_plural": "Mission_3",
                "db_table": "Mission_3",
            },
        ),
        migrations.CreateModel(
            name="Mission_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="팀명"
                    ),
                ),
                (
                    "team_members",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="팀원"
                    ),
                ),
                (
                    "mission",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="미션설명"
                    ),
                ),
                (
                    "mission2_imagesrc1",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지1 주소"
                    ),
                ),
                (
                    "mission2_imagesrc2",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지2 주소"
                    ),
                ),
                (
                    "mission2_imagesrc3",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지3 주소"
                    ),
                ),
                (
                    "mission2_imagesrc4",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지4 주소"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="아이디",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission_2",
                "verbose_name_plural": "Mission_2",
                "db_table": "Mission_2",
            },
        ),
        migrations.CreateModel(
            name="Mission_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="팀명"
                    ),
                ),
                (
                    "team_members",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="팀원"
                    ),
                ),
                (
                    "mission",
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name="미션설명"
                    ),
                ),
                (
                    "mission1_imagesrc1",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지1 주소"
                    ),
                ),
                (
                    "mission1_imagesrc2",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지2 주소"
                    ),
                ),
                (
                    "mission1_imagesrc3",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지3 주소"
                    ),
                ),
                (
                    "mission1_imagesrc4",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지4 주소"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="아이디",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission_1",
                "verbose_name_plural": "Mission_1",
                "db_table": "Mission_1",
            },
        ),
    ]
