# Generated by Django 4.1 on 2022-09-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission_1",
            name="group",
            field=models.CharField(max_length=6, null=True, verbose_name="그룹"),
        ),
        migrations.AddField(
            model_name="mission_2",
            name="group",
            field=models.CharField(max_length=6, null=True, verbose_name="그룹"),
        ),
        migrations.AddField(
            model_name="mission_3",
            name="group",
            field=models.CharField(max_length=6, null=True, verbose_name="그룹"),
        ),
        migrations.AddField(
            model_name="mission_4",
            name="group",
            field=models.CharField(max_length=6, null=True, verbose_name="그룹"),
        ),
    ]
