# Generated by Django 4.1 on 2022-09-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_mission_1_group_mission_2_group_mission_3_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission_1",
            name="group",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("D", "D"),
                    ("C", "C"),
                    ("B", "B"),
                    ("A", "A"),
                ],
                max_length=6,
                null=True,
                verbose_name="그룹",
            ),
        ),
        migrations.AlterField(
            model_name="mission_1",
            name="mission",
            field=models.TextField(
                blank=True, max_length=600, null=True, verbose_name="미션설명"
            ),
        ),
        migrations.AlterField(
            model_name="mission_2",
            name="group",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("D", "D"),
                    ("C", "C"),
                    ("B", "B"),
                    ("A", "A"),
                ],
                max_length=6,
                null=True,
                verbose_name="그룹",
            ),
        ),
        migrations.AlterField(
            model_name="mission_2",
            name="mission",
            field=models.TextField(
                blank=True, max_length=600, null=True, verbose_name="미션설명"
            ),
        ),
        migrations.AlterField(
            model_name="mission_3",
            name="group",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("D", "D"),
                    ("C", "C"),
                    ("B", "B"),
                    ("A", "A"),
                ],
                max_length=6,
                null=True,
                verbose_name="그룹",
            ),
        ),
        migrations.AlterField(
            model_name="mission_3",
            name="mission",
            field=models.TextField(
                blank=True, max_length=600, null=True, verbose_name="미션설명"
            ),
        ),
        migrations.AlterField(
            model_name="mission_4",
            name="group",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("D", "D"),
                    ("C", "C"),
                    ("B", "B"),
                    ("A", "A"),
                ],
                max_length=6,
                null=True,
                verbose_name="그룹",
            ),
        ),
        migrations.AlterField(
            model_name="mission_4",
            name="mission",
            field=models.TextField(
                blank=True, max_length=600, null=True, verbose_name="미션설명"
            ),
        ),
    ]
