# Generated by Django 4.1 on 2022-09-05 23:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_mission_1_group_alter_mission_1_mission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission_1",
            name="mission",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
