# Generated by Django 4.1 on 2022-09-06 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0004_alter_mission_1_mission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission_5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("NONE", "NONE"),
                            ("D", "D"),
                            ("C", "C"),
                            ("B", "B"),
                            ("A", "A"),
                        ],
                        max_length=6,
                        null=True,
                        verbose_name="그룹",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="팀명"
                    ),
                ),
                (
                    "team_members",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="팀원"
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True, max_length=600, null=True, verbose_name="미션설명"
                    ),
                ),
                (
                    "mission5_imagesrc1",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지1 주소"
                    ),
                ),
                (
                    "mission5_imagesrc2",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지2 주소"
                    ),
                ),
                (
                    "mission5_imagesrc3",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지3 주소"
                    ),
                ),
                (
                    "mission5_imagesrc4",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="이미지4 주소"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="아이디",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission_5",
                "verbose_name_plural": "Mission_5",
                "db_table": "Mission_5",
            },
        ),
    ]
