# Generated by Django 4.1 on 2022-09-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_mission_5"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mission_1",
            old_name="mission1_imagesrc2",
            new_name="mission_imagesrc2",
        ),
        migrations.RenameField(
            model_name="mission_1",
            old_name="mission1_imagesrc3",
            new_name="mission_imagesrc3",
        ),
        migrations.RenameField(
            model_name="mission_1",
            old_name="mission1_imagesrc4",
            new_name="mission_imagesrc4",
        ),
        migrations.RenameField(
            model_name="mission_1",
            old_name="mission1_imagesrc1",
            new_name="thumbnail_imagesrc1",
        ),
        migrations.RenameField(
            model_name="mission_2",
            old_name="mission2_imagesrc2",
            new_name="mission_imagesrc2",
        ),
        migrations.RenameField(
            model_name="mission_2",
            old_name="mission2_imagesrc3",
            new_name="mission_imagesrc3",
        ),
        migrations.RenameField(
            model_name="mission_2",
            old_name="mission2_imagesrc4",
            new_name="mission_imagesrc4",
        ),
        migrations.RenameField(
            model_name="mission_2",
            old_name="mission2_imagesrc1",
            new_name="thumbnail_imagesrc1",
        ),
        migrations.RenameField(
            model_name="mission_3",
            old_name="mission3_imagesrc2",
            new_name="mission_imagesrc2",
        ),
        migrations.RenameField(
            model_name="mission_3",
            old_name="mission3_imagesrc3",
            new_name="mission_imagesrc3",
        ),
        migrations.RenameField(
            model_name="mission_3",
            old_name="mission3_imagesrc4",
            new_name="mission_imagesrc4",
        ),
        migrations.RenameField(
            model_name="mission_3",
            old_name="mission3_imagesrc1",
            new_name="thumbnail_imagesrc1",
        ),
        migrations.RenameField(
            model_name="mission_4",
            old_name="mission4_imagesrc2",
            new_name="mission_imagesrc2",
        ),
        migrations.RenameField(
            model_name="mission_4",
            old_name="mission4_imagesrc3",
            new_name="mission_imagesrc3",
        ),
        migrations.RenameField(
            model_name="mission_4",
            old_name="mission4_imagesrc4",
            new_name="mission_imagesrc4",
        ),
        migrations.RenameField(
            model_name="mission_4",
            old_name="mission4_imagesrc1",
            new_name="thumbnail_imagesrc1",
        ),
        migrations.RenameField(
            model_name="mission_5",
            old_name="mission5_imagesrc2",
            new_name="mission_imagesrc2",
        ),
        migrations.RenameField(
            model_name="mission_5",
            old_name="mission5_imagesrc3",
            new_name="mission_imagesrc3",
        ),
        migrations.RenameField(
            model_name="mission_5",
            old_name="mission5_imagesrc4",
            new_name="mission_imagesrc4",
        ),
        migrations.RenameField(
            model_name="mission_5",
            old_name="mission5_imagesrc1",
            new_name="thumbnail_imagesrc1",
        ),
    ]
