# Generated by Django 4.1 on 2022-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "board",
            "0006_rename_mission1_imagesrc2_mission_1_mission_imagesrc2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mission_1",
            name="end_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mission_2",
            name="end_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mission_3",
            name="end_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mission_4",
            name="end_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mission_5",
            name="end_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
