# Generated by Django 4.1 on 2022-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_alter_mission_2_mission_alter_mission_3_mission_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="mission_1", name="mission_imagesrc2",),
        migrations.RemoveField(model_name="mission_1", name="mission_imagesrc3",),
        migrations.RemoveField(model_name="mission_1", name="mission_imagesrc4",),
        migrations.RemoveField(model_name="mission_1", name="thumbnail_imagesrc1",),
        migrations.RemoveField(model_name="mission_2", name="mission_imagesrc2",),
        migrations.RemoveField(model_name="mission_2", name="mission_imagesrc3",),
        migrations.RemoveField(model_name="mission_2", name="mission_imagesrc4",),
        migrations.RemoveField(model_name="mission_2", name="thumbnail_imagesrc1",),
        migrations.RemoveField(model_name="mission_3", name="mission_imagesrc2",),
        migrations.RemoveField(model_name="mission_3", name="mission_imagesrc3",),
        migrations.RemoveField(model_name="mission_3", name="mission_imagesrc4",),
        migrations.RemoveField(model_name="mission_3", name="thumbnail_imagesrc1",),
        migrations.RemoveField(model_name="mission_4", name="mission_imagesrc2",),
        migrations.RemoveField(model_name="mission_4", name="mission_imagesrc3",),
        migrations.RemoveField(model_name="mission_4", name="mission_imagesrc4",),
        migrations.RemoveField(model_name="mission_4", name="thumbnail_imagesrc1",),
        migrations.RemoveField(model_name="mission_5", name="mission_imagesrc2",),
        migrations.RemoveField(model_name="mission_5", name="mission_imagesrc3",),
        migrations.RemoveField(model_name="mission_5", name="mission_imagesrc4",),
        migrations.RemoveField(model_name="mission_5", name="thumbnail_imagesrc1",),
        migrations.AddField(
            model_name="mission_1",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_image1/"
            ),
        ),
        migrations.AddField(
            model_name="mission_1",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_image2/"
            ),
        ),
        migrations.AddField(
            model_name="mission_1",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_1",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_thumbnail/"
            ),
        ),
        migrations.AddField(
            model_name="mission_2",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_image1/"
            ),
        ),
        migrations.AddField(
            model_name="mission_2",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_image2/"
            ),
        ),
        migrations.AddField(
            model_name="mission_2",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_2",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_thumbnail/"
            ),
        ),
        migrations.AddField(
            model_name="mission_3",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_image1/"
            ),
        ),
        migrations.AddField(
            model_name="mission_3",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_image2/"
            ),
        ),
        migrations.AddField(
            model_name="mission_3",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_3",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_thumbnail/"
            ),
        ),
        migrations.AddField(
            model_name="mission_4",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image1/"
            ),
        ),
        migrations.AddField(
            model_name="mission_4",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image2/"
            ),
        ),
        migrations.AddField(
            model_name="mission_4",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_4",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_thumbnail/"
            ),
        ),
        migrations.AddField(
            model_name="mission_5",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image1/"
            ),
        ),
        migrations.AddField(
            model_name="mission_5",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image2/"
            ),
        ),
        migrations.AddField(
            model_name="mission_5",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_5",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_thumbnail/"
            ),
        ),
    ]
