# Generated by Django 4.1 on 2022-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0009_remove_mission_1_mission_imagesrc2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="mission_1", name="thumbnail",),
        migrations.RemoveField(model_name="mission_2", name="thumbnail",),
        migrations.RemoveField(model_name="mission_3", name="thumbnail",),
        migrations.RemoveField(model_name="mission_4", name="thumbnail",),
        migrations.RemoveField(model_name="mission_5", name="thumbnail",),
        migrations.AddField(
            model_name="mission_1",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_2",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_3",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_4",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image3/"
            ),
        ),
        migrations.AddField(
            model_name="mission_5",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image3/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_1",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_thumbnail/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_1",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_image1/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_1",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission1_image2/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_2",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_thumbnail/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_2",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_image1/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_2",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission2_image2/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_3",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_thumbnail/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_3",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_image1/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_3",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission3_image2/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_4",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_thumbnail/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_4",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image1/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_4",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image2/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_5",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_thumbnail/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_5",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image1/"
            ),
        ),
        migrations.AlterField(
            model_name="mission_5",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="mission4_image2/"
            ),
        ),
    ]
