# Generated by Django 4.1 on 2022-09-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="level",
            field=models.CharField(
                choices=[
                    ("4", "참여자 (팀원)"),
                    ("3", "참여자 (팀장)"),
                    ("2", "기획단"),
                    ("1", "관리자"),
                    ("0", "개발자"),
                ],
                default=3,
                max_length=18,
                verbose_name="등급",
            ),
        ),
    ]
